# Generated by Django 4.1.6 on 2023-04-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255, null=True)),
                ('source_name', models.CharField(max_length=255, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(max_length=255, null=True)),
                ('urlToImage', models.URLField(max_length=255, null=True)),
                ('publishedAt', models.DateTimeField(null=True)),
                ('content', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('tags', models.TextField(null=True)),
            ],
        ),
    ]
